version: '3'
services:
  postgres.data:
    image: postgres:9.5
    container_name: postgres-server
    env_file:
      - postgres.env

  spring-task17:
    build: .
    container_name: myspring
    links:
      - postgres.data
    ports:
      - 8081:8080