application:
  url: http://localhost:8080
  hourValidateTokenForRegistration: 10
  emailName: Check email

  sms:
    mock: true
    login: martinstein150990
    password: alescha333

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:mydatabase
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.gmail.com
    port: 587
    username: martinstein150990@gmail.com
    password: alescha333
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

  management:
    endpoints:
      enabled-by-default: false
      web:
        exposure:
          include: '*'
          exclude: ''
        base-path: /info
    endpoint:
      env:
        enabled: true
      configprops:
        enabled: true
      liquibase:
        enabled: true
      metrics:
        enabled: true
      health:
        enabled: true
      logfile:
        enabled: true

  logging:
    pattern:
      file: '%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n'
    file: 'logs/log.log'