application:
  url: http://localhost:8080
  hourValidateTokenForRegistration: 10
  emailName: Check email

  sms:
    mock: true
    login: martinstein150990
    password: alescha333

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:mydatabase
    initialization-mode: always

  logging:
    level:
      org.springframework.web: INFO

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.gmail.com
    port: 587
    username: martinstein150990@gmail.com
    password: alescha333
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com