spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:mydatabaseH2
    initialization-mode: never

  logging:
    level:
      org.springframework.web: INFO

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  data:
    mongodb:
      authentication-database: none
      database: mydatabaseMongo
      port: 27017
      host: localhost

  batch:
    initialize-schema: ALWAYS
