spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:mydatabase
    initialization-mode: always

  logging:
    level:
      org.springframework.web: INFO

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate


  data:
    mongodb:
      authentication-database: none
      database: library
      port: 27017
      host: localhost